spring.ai.mcp.client.sse.connections:
  person-mcp-server:
    url: http://localhost:8060
  account-mcp-server:
    url: http://localhost:8040
spring:
  ai:
    ollama:
      chat:
        model: llama3.2